name: source_map_transformer
author: Boris Kaul <localvoid@gmail.com>
description: Source map transformer.
homepage: https://github.com/localvoid/source_map_transformer
version: 0.1.0
environment:
  sdk: '>=1.9.0'
dependencies:
  barback: '>=0.15.0 <0.16.0'
  crypto: '>=0.9.0 <0.10.0'
  path: '>=1.3.0 <1.4.0'
